before_install:
 - sudo apt-get install -y python-virtualenv
 - sudo apt-get install -y ant
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install planemo
 - planemo conda_init

script:
 - ant test
