---
- hosts: all
  vars:

    #####################
    # CRAN REPOS VALUES #
    #####################

    crandeb_repos: "deb http://mirrors.ebi.ac.uk/CRAN/bin/linux/ubuntu trusty/"
    crandeb_key: E084DAB9

  tasks:

    # It is primordial to strictly respect the order of the steps below.

    ###################################
    # 1. ANSIBLE PACKAGE DEPENDENCIES #
    ###################################

    # In this primary step, we install some packages needed by Ansible to run apt commands.

    - name: Install Packages needed for package installation
      apt: pkg={{item}} state=latest
      with_items:
        - aptitude # Needed by apt when using upgrade=yes
        - python-pycurl # Needed by apt_repository command

    ########################
    # 2. CRAN REPOS SET UP #
    ########################

    - name: Add CRAN to package repositories
      apt_repository: repo="{{crandeb_repos}}" state=present

    - name: Add CRAN key
      apt_key: keyserver=keyserver.ubuntu.com id={{crandeb_key}}

    ###########################################
    # 3. UPDATE & UPGRADE OF PACKAGE DATABASE #
    ###########################################

    - name: Update package database
      apt: update_cache=yes 

    - name: Upgrade packages
      apt: upgrade=yes

    ########################
    # 4. TOOL INSTALLATION #
    ########################

    - name: Install packages
      apt: pkg={{item}} state=latest
      when: ansible_os_family == 'Debian'
      with_items:
        - r-base
        - git

    - name: Install Bioconductor package 'ropls'
      command: R -e "source('http://www.bioconductor.org/biocLite.R'); biocLite('ropls')" creates=/usr/lib/R/library/ropls

#    - name: Clone tool
#      git: repo=https://github.com/workflow4metabolomics/multivariate dest=/files/multivariate version=docker